In [5]:
# 21/05/22
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore")

In [6]:
df=pd.read_csv(r'D:\AI\LibrariesForAI\Supervised_Learning\1_Simple_Linear_regression\homeprices.csv')

In [8]:
X_df= df.drop('price',axis='columns')
X_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [9]:
Y_df=df['price']
Y_df

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [10]:
lr=LinearRegression()
lr.fit(X_df,Y_df)

LinearRegression()

In [6]:
lr.coef_

array([135.78767123])

In [7]:
lr.intercept_

180616.43835616432

#### Pickle file

In [8]:
import pickle

In [10]:
with open("lr_model",'wb') as file:
    pickle.dump(lr,file)

In [12]:
with open("lr_model",'rb') as file:
    mp=pickle.load(file)

In [13]:
mp.coef_

array([135.78767123])

In [14]:
mp.predict([[5000]])

array([859554.79452055])

In [16]:
#### create a file named sample.jason with some code:
import json
samplejson={
    "name":"luminar",
    "place":"kochi",
    "phno":7034358135
}
json_object=json.dumps(samplejson)

In [17]:
with open("sample.json","w")as file:
    file.write(json_object)

In [20]:
with open("sample.json","r")as file:
    newdata= json.load(file)

In [21]:
newdata

{'name': 'luminar', 'place': 'kochi', 'phno': 7034358135}

#### Save trained model using Joblib

In [2]:
import joblib

In [11]:
joblib.dump(lr, 'model_joblib')

['model_joblib']

In [13]:
mj = joblib.load('model_joblib')

In [14]:
mj.coef_

array([135.78767123])

In [15]:
mj.intercept_

180616.43835616432

In [16]:
joblib.load('lr_model')

LinearRegression()