In [1]:
# 16/03/2022


In [2]:
# Install python package - Numpy

In [3]:
# pip install numpy

In [4]:
import numpy as np

In [5]:
myList=[1,2,3,4,5]

In [6]:
print(myList)

[1, 2, 3, 4, 5]


In [7]:
type(myList)

list

In [8]:
# dir(np)

In [9]:
# help(np)

In [10]:
arr=np.array(myList)

In [11]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
# 17/03/2022

# shape of array
# Numpy array indexing
# Access 2D array


In [13]:
# shape of array

arr.shape

(5,)

In [14]:
arr.size

5

In [15]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

arr=np.array([my_list1,my_list2,my_list3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [16]:
type(arr)

numpy.ndarray

In [17]:
arr.shape

(3, 5)

In [18]:
arr.size

15

In [19]:
# Numpy array indexing

my_list=[1,2,3,4,5]
arr=np.array(my_list)

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
print(arr[0])

1


In [22]:
print(arr[1])

2


In [23]:
print(arr[2],arr[3])

3 4


In [24]:
# Access 2D array

my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

arr=np.array([my_list1,my_list2,my_list3])


In [25]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [26]:
arr[0,2]

3

In [27]:
print("2nd element on 1st row :",arr[0,1])

2nd element on 1st row : 2


In [28]:
# Access the element on the 2nd row,5th column:

print(arr[1,4])

6


In [29]:
# create a 2D array
# print the variable
# get shape
# get size
# index: 1st row 1st element
# index 2nd row 3rd element

In [30]:
valArr=np.array([[1,2,3],[4,5,6]])
print(valArr,"\n")
print(valArr.shape,"\n")
print(valArr.size,"\n")
print(valArr[0,0],"\n")
print(valArr[1,2],"\n")

[[1 2 3]
 [4 5 6]] 

(2, 3) 

6 

1 

6 



In [31]:
# create a 5*5 array
# print the variable
# get shape
# get size
# index: 1st row 3rd element
# index 4th row 2nd element

In [32]:
newArr=np.array([[1,2,3,4,5],[2,4,6,8,10],[6,7,8,9,11],[12,13,14,15,16],[10,20,30,40,50]])
print(newArr)
print(newArr.shape)
print(newArr.size)
print(newArr[0,2])
print(newArr[3,1])

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 6  7  8  9 11]
 [12 13 14 15 16]
 [10 20 30 40 50]]
(5, 5)
25
3
13


In [33]:
# 21/03/2022

# negative indexing
# Numpy Array Slicing -1D
# slicing 2D Array
# Arange function
# Linspace
# Numpy Data Types

In [34]:
# negative indexing

my_list=[1,2,3,4,5,6,7]
arr=np.array(my_list)

#print(arr)


valArr=np.array([[1,2,3],[4,5,6]])
print(valArr)

[[1 2 3]
 [4 5 6]]


In [35]:
valArr[0,-1]

3

In [36]:
valArr[1,-2]

5

In [37]:
# Numpy Array Slicing -1D

my_list=[1,2,3,4,5,6,7,8,9,10]
arr=np.array(my_list)

print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [38]:
# arr[start:end]
arr[0:4]

array([1, 2, 3, 4])

In [39]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [40]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[-3:-1]

array([8, 9])

In [42]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
# step
arr[::2]

array([1, 3, 5, 7, 9])

In [44]:
arr[1::2]

array([ 2,  4,  6,  8, 10])

In [45]:
arr[1::3]

array([2, 5, 8])

In [46]:
# slicing 2D Array

my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

arr=np.array([my_list1,my_list2,my_list3])

print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [47]:
arr[1:,:]

array([[2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [48]:
arr[:2,1:4]

array([[2, 3, 4],
       [3, 4, 5]])

In [49]:
arr[:,1:4]

array([[2, 3, 4],
       [3, 4, 5],
       [7, 6, 8]])

In [50]:
# Arange function


np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [52]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [53]:
# Linspace

np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [54]:
# Numpy Data Types

In [55]:
arr=np.array([1,2,3,4])
print(arr.dtype)

int32


In [56]:
arr=np.array([1.0,2.0])
print(arr.dtype)

float64


In [57]:
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [58]:
arr=np.array(['apple','banana','bananacherry'])
print(arr.dtype)

<U12


In [59]:
#22/03/2022


In [60]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [61]:
arr=np.array([1,2,3,4,5],dtype=np.int64)
print(arr.dtype)

int64


In [62]:
arr=np.array([1,2,3,4,5],dtype=np.float32)
print(arr.dtype)

float32


In [63]:
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [64]:
# Array Math

x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [65]:
print(x)
print("**")
print(y)

[[1 2]
 [3 4]]
**
[[5 6]
 [7 8]]


In [66]:
x+y

array([[ 6,  8],
       [10, 12]])

In [67]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [68]:
x-y

array([[-4, -4],
       [-4, -4]])

In [69]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [70]:
x*y

array([[ 5, 12],
       [21, 32]])

In [71]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [72]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [73]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [74]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [75]:
np.sqrt(y)

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [77]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])


In [78]:
x.shape

(2, 2)

In [79]:
y.shape

(2, 2)

In [80]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [81]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [82]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [83]:
x

array([[1, 2],
       [3, 4]])

In [84]:
np.exp(x)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [85]:
np.log(x)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [86]:
np.cos(x)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [87]:
np.sin(x)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [88]:
np.tan(x)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [89]:
# Floor,Ceil,Round

x= np.array([[1.5,2.5],[3.1,4.9]], dtype=np.float64)

In [90]:
x

array([[1.5, 2.5],
       [3.1, 4.9]])

In [91]:
np.floor(x)

array([[1., 2.],
       [3., 4.]])

In [92]:
np.ceil(x)

array([[2., 3.],
       [4., 5.]])

In [93]:
np.round(x)

array([[2., 2.],
       [3., 5.]])